version: "3.8"
services:
  server:
    image: jewelry-shop
    container_name: "jewelry-shop"
    build: ./Dockerfile
    volumes:
      - ./.build/volumes/logs:/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgre__todo.todo

  postgre__todo.todo:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - /var/postgre__todo.todo:/var/lib/postgresql/data
    ports:
      - "2000:5432"
    restart: always
